### ISSUE TITLE
LibSVM fails at apply time unless probabilistic

### ISSUE THREAD

**Issue by GenevieveGorrell** [GenevieveGorrell/gateplugin-LearningFramework#1]
Unless LibSVM parameter is set to -b 1 (i.e. create a probabilistic SVM) the PR fails at apply time like so:

java.lang.ArrayIndexOutOfBoundsException: 4
    at libsvm.svm.svm_predict_values(svm.java:2378)
    at gate.learningframework.EngineLibSVM.classify(EngineLibSVM.java:372)
    at gate.learningframework.LearningFrameworkPR.execute(LearningFrameworkPR.java:553)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.creole.ConditionalSerialController.runComponent(ConditionalSerialController.java:163)
    at gate.creole.SerialController.executeImpl(SerialController.java:157)
    at gate.creole.ConditionalSerialAnalyserController.executeImpl(ConditionalSerialAnalyserController.java:225)
    at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:132)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1728)
    at java.lang.Thread.run(Thread.java:744)

**Comment by GenevieveGorrell** [comment]
This is solved. Non-probabilistic LibSVM models are now possible. There is no longer any attempt to supply the decision value for non-prob SVMs since these values seem to arise in the context of a one-vs-another multiclass to binary problem mapping, so there isn't simply one value per class that can easily be supplied along with the class choice, as in a probabilistic model, but instead a more complex array of values as described here: http://www.csie.ntu.edu.tw/~r94100/libsvm-2.8/README
